#!/bin/python3

#python script to display files

import tkinter as tk
from tkinter.ttk import Style, Button
from markdown2 import Markdown
from tkhtmlview import HTMLLabel
from os import listdir, path

current_index = 0

def getListOfFiles(dirName):
    # https://thispointer.com/python-how-to-get-list-of-files-in-directory-and-sub-directories/
    # create a list of file and sub directories 
    # names in the given directory 
    listOfFile = listdir(dirName)
    allFiles:list[str] = []
    # Iterate over all the entries
    for entry in listOfFile:
        # Create full path
        fullPath:str = path.join(dirName, entry)
        # If entry is a directory then get the list of files in this directory 
        if path.isdir(fullPath):
            allFiles = allFiles + getListOfFiles(fullPath)
        else:
            allFiles.append(fullPath)
                
    return allFiles


files = getListOfFiles("./4th_semester")
files.reverse()

content = []
md_files:list[str] = []
for file in files:
    if not file.find(".md") == -1:
        md_files.append(file)
        with open(file) as file:
            content.append(file.read())

def next(label:HTMLLabel):
    global current_index
    if not len(content) == current_index + 1:
        current_index = current_index + 1
    else:
        current_index = 0
    label.set_html(md2html.convert(content[current_index]))

def previous(label:HTMLLabel):
    global current_index
    if not current_index == 0:
        current_index = current_index - 1
    else:
        current_index = len(content) - 1
    label.set_html(md2html.convert(content[current_index]))


main = tk.Tk()
style = Style(main)
try:
    style.theme_use("breeze-dark")
except:
    print("trying windows theme")
    try:
        style.theme_use("vista")
    except:
        print("failed to set theme, setting to default")
md2html = Markdown()
html = HTMLLabel(main, width=100, height=50)
html.pack(side="left")
html.set_html(md2html.convert(content[0]))
next_prev_frame = tk.Frame(main)
prev_button = Button(next_prev_frame, text="Previous", command=lambda: previous(html))
prev_button.pack(side="left")
next_button = Button(next_prev_frame, text="Next", command=lambda: next(html))
next_button.pack(side="left")
next_prev_frame.pack(side="bottom")



class specific():
    def __init__(self, index):
        self.index = index

    def set_specific(self):
        file = md_files[self.index]
        with open(file) as file:
            html.set_html(md2html.convert(file.read()))



# specific files
button_frame = tk.Frame(main)
button_frame.pack(side="right")
buttons = []
for i in range(len(md_files)):
    obj = specific(i)
    split_string = md_files[i].split("/")
    title =split_string[len(split_string) - 2] + "/" + split_string[len(split_string) - 1]
    buttons.append(Button(button_frame, text=title, command=obj.set_specific, width=40))
    buttons[i].pack(side="top")


main.mainloop()
